# Generated by Django 5.1.2 on 2024-11-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='duration',
        ),
    ]
