# Generated by Django 5.1.2 on 2024-12-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscriptionplan_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-start_date']},
        ),
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='price',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ref',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
