# Generated by Django 5.1.2 on 2024-12-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
