# Generated by Django 5.1.2 on 2025-01-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_alter_subscription_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='verified',
        ),
        migrations.AddField(
            model_name='subscription',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
