# Generated by Django 5.1.2 on 2025-01-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_remove_subscriptionplan_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
