# Generated by Django 5.1.2 on 2024-10-31 10:01

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0002_classes_subject_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, unique=True)),
                ('description', models.CharField(max_length=250, null=True, unique=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.classes')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lesson.chapters')),
                ('chapter_content', tinymce.models.HTMLField()),
            ],
        ),
    ]
