# Generated by Django 5.1.2 on 2024-10-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, unique=True)),
                ('image', models.ImageField(null=True, upload_to='images/subjects_upload')),
                ('description', models.CharField(default='', max_length=800, null=True)),
                ('slug', models.SlugField(default='', null=True, unique=True)),
            ],
        ),
    ]
