# Generated by Django 5.1.2 on 2024-11-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_classes_subject_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='form',
            field=models.ManyToManyField(related_name='subjects', to='subject.classes'),
        ),
    ]
